### ISSUE TITLE
Multiworld on EverDrive

### ISSUE THREAD

**Issue by fenhl** [TestRunnerSRL/OoT-Randomizer#2042]
Now that we have a proof of concept of communicating with the game via the EverDrive's USB protocol ([PC side](https://github.com/fenhl/everdrive-test), [N64 side](https://github.com/fenhl/OoT-Randomizer/tree/everdrive)), it's time to figure out what the communication protocol is supposed to look like. Here's my current draft:

# Design notes

All PC→N64 packets are exactly 16 bytes long to simplify the receiving code on the N64 side. N64→PC packets may be of any size supported by the EverDrive, i.e. anywhere between 16 and 512 bytes; the packet's size depends on its ID (first byte). This is because we may want to have N64 send large amounts of data when a file is selected, to make auto-tracking integration work. Unless noted otherwise, packets in either direction with a total length less than 16 bytes are padded with trailing zero bytes which are reserved for use in future versions of the protocol.

The protocol must seamlessly recover from state loss due to console reset. Fortunately, the console being reset causes the PC to see an existing connection as timed out even if the game is restarted within the timeout. It can then reconnect and start over. To achieve this, N64 sends periodic pings (every 100 frames, which corresponds to every 5 seconds while in-game and not paused), and PC sets a read timeout of 10 seconds (twice the ping interval).

# Handshake

1. Communication is initiated by PC sending ASCII `cmdt` followed by a null suffix. The format of this handshake is chosen to also be a valid command if N64 is in the EverDrive's main menu, which allows PC to determine the console's state based on the reply. The suffix must remain null in future versions for compatibility with the main menu.
2. N64 sends ASCII `OoTR` followed by:
    * The protocol version byte (currently `0x01`). If PC does not support this protocol version, it must close the connection now, any reply indicates support for this version.
    * `get_version_bytes`, i.e. a 5-byte sequence encoding the randomizer version number: major, minor, patch, [branch identifier](https://wiki.ootrandomizer.com/index.php?title=Branch_identifiers), supplementary version.
    * The world number (1-indexed).
    * `CFG_FILE_SELECT_HASH`, i.e. the 5 icons displayed at the top of the file select screen, represented as indices into the `HASH_ICONS` list in Spoiler.py.

    If PC instead receives ASCII `cmdr` or `cmdk`, the N64 is in the EverDrive main menu. PC can either continue to use this connection via the main menu protocol, or disconnect and retry after an amount of time.
3. PC sends ASCII `MW` followed by:
    * the protocol version byte (must be the same one that was received)
    * `MW_SEND_OWN_ITEMS` (a Boolean flag indicating whether to enable this feature)
    * `MW_PROGRESSIVE_ITEMS_ENABLE` (a Boolean flag indicating whether to enable this feature)

    This step is designed to allow reusing the handshake for something other than multiworld, e.g. auto-tracking, debugging, or crowd control. For those alternative use-cases, the PC would respond with a different packet prefix here, and the “normal operation” part of this protocol would be ignored in favor of a different protocol for the given purpose.
4. Normal operation commences with N64 sending a state packet and PC simultaneously sending player names. Once PC has received the state packet, it may also immediately send items to restore the queue. More info in the following two sections.

# Normal operation: PC→N64

The following packet IDs are used:

* `0x00` Ping
    * sent every 5 seconds
* `0x01` Player Data
    * the world number (1 byte)
    * the player name (8 bytes in OoT's internal player name format)
    * progressive items state (4 bytes, see `mw_progressive_items_state_t` in `item_upgrades.c`, PC may set this to 0 if `MW_PROGRESSIVE_ITEMS_ENABLE` is off)
* `0x02` Get Item
    * item kind (2 bytes)
    * Only one item may be sent after each time the N64 sends “State: In Game” or “Item Received”, and only items past the internal item count are sent
* `0x63` (ASCII `c`) indicates that PC has reset (e.g. the multiworld app has been relaunched). N64 should reset its connection state and treat the incoming packet as the first part of a new handshake.

# Normal operation: N64→PC

The following packet IDs are used:

* `0x00` Ping
    * sent every 5 seconds
* `0x01` State: File Select
    * the player name: 8 bytes in the internal player name format, 8 spaces (`DFDFDFDFDFDFDFDF`) if not set
    * Sent after completion of the handshake if not ingame, or if the selected filename changes
* `0x02` State: In Game
    * first part of save data (200 bytes)
    * Sent after completion of the handshake if ingame, or if a file is opened. Should be followed by 10 Save Data Segment (`0x06`) packets.
* `0x03` Send Item
    * override key (8 bytes)
    * item kind (2 bytes)
    * target world (1 byte)
* `0x04` Item Received
    * tells PC that another Get Item packet may be sent
* `0x05` Dungeon Reward Locations
    * For each dungeon reward, in order of Emerald, Ruby, Sapphire, Light, Forest, Fire, Water, Shadow, Spirit:
      * optional world (1 byte)
      * optional hint area (1 byte)
    * Sent when the player is looking at the A or D-down menu on the inventory subscreen and the info shown there has changed
* `0x06` Save Data Segment
    * save data segment index, between 0 and 9 inclusive (1 byte)
    * corresponding part of save data (500 bytes)
    * Sent 10 times immediately after sending a State: In Game (`0x02`) packet, for a total of 5200 (`0x1450`) bytes, which is the size of an OoT save file.

# TODO

- [ ] Feature parity with MH MW for emulators
    - [x] on file load, send the subset of save data required for auto-tracking and maintaining progressive items state
        * I've decided that sending the entire save data is best for forward compatibility.
    - [ ] send current scene
    - [ ] check if there's anything else missing
- [ ] Ensure docs of both multiworld interfaces mention that the other needs to be updated at the same time

**Comment by Polprzewodnikowy** [comment]
What about flashcarts other than EverDrive64? N64 homebrew community has developed an universal USB library - [UNFLoader](https://github.com/buu342/N64-UNFLoader) - that supports most common flashcarts available on the market. It's been successfully integrated in several projects, including:
- [libdragon](https://github.com/DragonMinded/libdragon)
- [n64sdkmod](https://github.com/ModernN64SDK/n64sdkmod)
- [HackerSM64](https://github.com/HackerN64/HackerSM64)
- [64dddump](https://github.com/LuigiBlood/64dddump)

Locking this feature to EverDrive64 v3/X7 doesn't really make sense since other flashcarts (64drive/SummerCart64) include USB port as a standard feature, while most EverDrive64 models out there doesn't even have this port available.

**Comment by fenhl** [comment]
I'm not familiar enough with projects like libultra and libdragon to be able to integrate this into OoTR, but I think if someone were to contribute support for these additional flashcarts, it would most likely be accepted.

**Comment by fenhl** [comment]
The current work-in-progress implementation of this protocol can be found on [my fork of the randomizer](https://github.com/fenhl/OoT-Randomizer).

**Comment by mracsys** [comment]
I looked at the examples in UNFLoader's repo. With some tweaks it could be brought over.

OoT includes parts of libultra. I added usb.c from UNFLoader's libultra usage example to Fenhl's branch and got it to compile, though no idea yet if it works. I haven't finished porting the read/write functionality in everdrive.c over to the library yet. There were also a handful of functions I had to grab from the libultra decomp as OoT did not include them from what I could tell. WIP is here: https://github.com/mracsys/OoT-Randomizer/tree/summercart_mw_support

As part of the abstraction between carts, communication back and forth over the wire is unfortunately not standardized. Examples are everdrives including `DMA@` and `CMPH` headers/footers and 64drives padding out blocks to align to 4 bytes (and stripping those bytes back out based on the data header). It would need Mido's House to add a dependency to UNFLoader's flashcart library (already available separate from the rest of the project), or modify the protocol to standardize/remove headers and manually add support for each flashcart on MH's side.

The interface itself seems like a worthwhile upgrade even if we only used the everdrive support. It supports a much larger buffer that could be useful for autotrackers syncing initial save data in one request.

I'd be happy to contribute changes to MH to support this. Is there a preferred approach?

**Comment by fenhl** [comment]
If this would make it easier to support multiple flashcarts, I think it's a good idea, but I've asked the rest of the team for their opinions as well.

**Comment by fenhl** [comment]
Would this approach still be able to support transparent handling of EverDrive's main menu protocol?

**Comment by mracsys** [comment]
Yes, initializing the library ROM-side sends a heartbeat packet that the client can listen for (currently `0x05XXXXXX00020001`, where 05 is the heartbeat datatype, X is the size of the transfer aligned based on specific cart requirements, 0002 is the USB protocol version, and 0001 is the heartbeat version). No need to send data that could be misinterpreted by any of the cart menus.

**Comment by mracsys** [comment]
Some more details, the library does not expose a generic “send command” function. For everdrive, every message starts with `DMA@xxyyyyyy` followed by the payload, where x is the data type and y is the payload length, including header. I don’t know how the everdrive menu behaves if it receives a payload with a valid command `cmd*`somewhere, or if it only recognizes commands as the beginning of any given transmission. I’ll look into that more.

**Comment by mracsys** [comment]
It works! At least on Windows. N64 -> PC worked on Fedora, but not the the other way around, even with sudo. Probably the udev rules I ignored in the setup script for UNFLoader. I'll check that later.

Handling the menus has a minor hiccup on Everdrives. The PC-side read function needed to check for a heartbeat from the ROM will hang until a ROM is selected in the menu. It does resume uninterrupted after that, so I'm not sure it's an actual problem. Summercart doesn't block anything, but it does transmit some debug text when selecting a ROM and loading a ROM. That should be straightforward to detect and ignore.

There is a bug in the upstream ROM-side Summercart write function here: https://github.com/buu342/N64-UNFLoader/blob/8a371c551a0f1af2f4351ad6d7fb877c6ac8e29b/USB%2BDebug%20Library/usb.c#L1487. This should be `MAX`, not `MIN`. As-is, the ROM crashes on the memcpy from the provided heartbeat data to the usb buffer when trying to send the first heartbeat after initializing. I'll PR that back to them when I get a chance to clean things up.

Otherwise, the only gotcha for library usage I found is the protocol version has to be set to 2 as the ROM-side functions don't handle V1. This only affects Everdrives.

Really messy proof of concept is in these two repos for the rando changes and a barebones PC client that gives Light Arrows 10 seconds after negotiating:
https://github.com/mracsys/OoT-Randomizer/tree/summercart_mw_support
https://github.com/mracsys/n64usb
The PC client is in Rust to facilitate updating Mido's House eventually if this library gets used.
The rando branch has a bunch of multiworld stuff still commented out as well as some debug code left. I'll clean things up when I get the chance.

I tested on a Summercart (N64FlashcartMenu 0.3.1), Everdrive X7 (OS 3.10), and Everdrive V3 (OS 3.06).

**Comment by mracsys** [comment]
Linux problem was permissions. Adding myself to dialout worked. It's also working on macos. Still need to clean things up.

**Comment by mracsys** [comment]
Proof of concept is finished at the two repos listed before. The flashcart library wrapper is separated into it's own `n64flashcart` crate that can be referenced by Mido's House. I'll work on rebasing the rando changes to current dev-fenhl in a bit.
